# Generated by Django 3.2.13 on 2022-07-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('slug', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('cellar_name', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=256)),
                ('zone', models.CharField(max_length=256)),
                ('varieties', models.TextField(blank=True)),
                ('wine_type', models.CharField(blank=True, max_length=256)),
                ('wine_type_simple', models.CharField(blank=True, max_length=256)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ecologic', models.BooleanField()),
                ('penin_points', models.PositiveIntegerField()),
                ('tasting_date', models.DateField(blank=True, null=True)),
                ('style', models.TextField(blank=True)),
                ('mouth', models.TextField(blank=True)),
                ('color', models.TextField(blank=True)),
                ('smell', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
