# Generated by Django 3.2.13 on 2022-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='axii',
            field=models.CharField(blank=True, default=None, max_length=63, null=True),
        ),
    ]
